POST http://localhost:3001/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZhc3RhcGFhdmkiLCJpZCI6IjVhODU5NzI2ZWZjMDczM2NhMTFhMmRiNCIsImlhdCI6MTUxODcxNDEyMn0.PKksIF_4XBLJmh0A9FzYzXmqPRxP4sQfLPpqsok_n-E

{
  "title": "tokenExtractor 2",
  "author": "mister",
  "url": "http://web",
  "likes": "3"
}